--- 
javascripts: 
- base: 
  - ui.datepicker-pt-BR
  - select_boxes
  - jrails
  - jquery.price_format.1.0
  - jquery.loading.1.6.4.min
  - application
  - jquery.tablesorter.min
stylesheets: 
- base: 
  - adm
  - jquery.loading.1.6
  - jquery
  - jquery.ui.base
